Задание 1 (синтаксис)

Для каждого покупателя получите таблицу со столбцами:
 • preferred_payment - самый частый метод оплаты (при ничьей зафиксируйте правило, например lexicographically первый);
 • total_spent - сумма всех трат;
 • addons_spent - сумма на дополнительные услуги и аксессуары;
 • orders_count - число заказов.
 
Отсортируйте по total_spent по убыванию и выведите топ-10.

Пример вывода (формат; числа зависят от датасета):

   customer_id  preferred_payment  total_spent  addons_spent  orders_count
 0         C042     Credit Card              15420.50        890.00             7
 1         C018     PayPal                     14810.00        450.00             5
 2         C103     Debit Card               13990.25       1200.00             6
 ...

Пограничные случаи:

• Покупатель с одним заказом - orders_count = 1, preferred_payment = единственный метод.
• Два метода оплаты с одинаковой частотой - выберите один по зафиксированному правилу (укажите его в комментарии к коду).
• Покупатель без доп. услуг/аксессуаров - addons_spent = 0.
• Пропуски в сумме или методе оплаты - обработайте (отфильтруйте или заполните) и кратко опишите решение в комментарии.

In [3]:
import pandas as pd

In [4]:
electronic_devices_sales_path = 'Electronic_sales_Sep2023-Sep2024.csv'

In [5]:
electronic_devices_sales = pd.read_csv(electronic_devices_sales_path)

In [7]:
electronic_devices_sales.head()

,Customer ID,Age,Gender,Loyalty Member,Product Type,SKU,Rating,Order Status,Payment Method,Total Price,Unit Price,Quantity,Purchase Date,Shipping Type,Add-ons Purchased,Add-on Total
0,1000,53,Male,No,Smartphone,SKU1004,2,Cancelled,Credit Card,5538.33,791.19,7,2024-03-20,Standard,"Accessory,Accessory,Accessory",40.21
1,1000,53,Male,No,Tablet,SKU1002,3,Completed,Paypal,741.09,247.03,3,2024-04-20,Overnight,Impulse Item,26.09
2,1002,41,Male,No,Laptop,SKU1005,3,Completed,Credit Card,1855.84,463.96,4,2023-10-17,Express,NaN,0.00
3,1002,41,Male,Yes,Smartphone,SKU1004,2,Completed,Cash,3164.76,791.19,4,2024-08-09,Overnight,"Impulse Item,Impulse Item",60.16
4,1003,75,Male,Yes,Smartphone,SKU1001,5,Completed,Cash,41.50,20.75,2,2024-05-21,Express,Accessory,35.56

In [8]:
electronic_devices_sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Customer ID        20000 non-null  int64
 1   Age                20000 non-null  int64
 2   Gender             19999 non-null  str
 3   Loyalty Member     20000 non-null  str
 4   Product Type       20000 non-null  str
 5   SKU                20000 non-null  str
 6   Rating             20000 non-null  int64
 7   Order Status       20000 non-null  str
 8   Payment Method     20000 non-null  str
 9   Total Price        20000 non-null  float64
 10  Unit Price         20000 non-null  float64
 11  Quantity           20000 non-null  int64
 12  Purchase Date      20000 non-null  str
 13  Shipping Type      20000 non-null  str
 14  Add-ons Purchased  15132 non-null  str
 15  Add-on Total       20000 non-null  float64
dtypes: float64(3), int64(4), str(9)
memory usage: 3.9 MB

Посчитаем следующие показатели: 
    • total_spent - сумма всех трат
    • addons_spent - сумма на дополнительные услуги и аксессуары
    • orders_count - число заказов

In [17]:
electronic_devices_sales_stats = (
    electronic_devices_sales
        .groupby("Customer ID")
        .agg (
            total_spent = ("Total Price", "sum"),
            addons_spent = ("Add-on Total", "sum"),
            orders_count = ("Customer ID","count"),
            preferred_payment=('Payment Method', get_preferred_payment)
        ))

             total_spent  addons_spent  orders_count preferred_payment
Customer ID
1000             6279.42         66.30             2       Credit Card
1002             5020.60         60.16             2              Cash
1003               41.50         35.56             1              Cash
1004               83.00         65.78             1       Credit Card
1005            11779.11         75.33             2        Debit Card
1006            12184.27        133.43             3              Cash
1007             7120.71         55.48             1       Credit Card
1008             3379.32         65.85             1              Cash
1011             7911.90         70.17             1       Credit Card
1013             5538.33         57.81             1            Paypal

Функция для поиска самого частого способа оплаты. При равной частоте способов оплаты берем первый по алфавиту:

In [16]:
def get_preferred_payment(series):
    sorted_method = series.sort_values()
    counts = sorted_method.value_counts()
    return counts.index[0]

In [18]:
electronic_devices_sales_stats = electronic_devices_sales_stats.sort_values(by='total_spent', ascending=False)

In [19]:
electronic_devices_sales_stats.head(10)

             total_spent  addons_spent  orders_count preferred_payment
Customer ID
16357           34563.70        495.19             7     Bank Transfer
16863           33035.92        486.17             5            PayPal
13813           31830.16        268.64             5       Credit Card
11476           31077.61        301.59             5            PayPal
12276           30961.18        329.07             6     Bank Transfer
13635           30260.36        480.73             5       Credit Card
12749           29394.56        619.43             5       Credit Card
15399           29084.88        305.39             3            PayPal
12319           27352.32        226.38             3     Bank Transfer
19996           27296.78        432.12             6     Bank Transfer